
export const materias = [
  { id:1,  nombre:'Matemática',             cuatrimestre:0,  requisitos:[] },
  { id:2,  nombre:'Física y Química',       cuatrimestre:0,  requisitos:[] },
  { id:3,  nombre:'Ambientación Univ.',     cuatrimestre:0,  requisitos:[] },
  { id:4,  nombre:'Fundamentos de Prog.',   cuatrimestre:1,  requisitos:[1] },
  { id:5,  nombre:'Análisis Mat. 1',        cuatrimestre:1,  requisitos:[1] },
  { id:6,  nombre:'Taller y Laboratorio',   cuatrimestre:1,  requisitos:[1, 3] },
  { id:7,  nombre:'Estructuras Discretas',  cuatrimestre:1,  requisitos:[1] },
  { id:8,  nombre:'Álgebra Lineal',         cuatrimestre:2,  requisitos:[1] },
  { id:9,  nombre:'Física 1',               cuatrimestre:2,  requisitos:[2, 5] },
  { id:10, nombre:'Módulo de Inglés',       cuatrimestre:2,  requisitos:[], requisitoCantidad:5 },
  { id:11, nombre:'Alg. y Est. de Datos',   cuatrimestre:2,  requisitos:[4, 7] },
  { id:12, nombre:'Análisis Mat. 2',        cuatrimestre:3,  requisitos:[5, 8] },
  { id:13, nombre:'Prog. Avanzada',         cuatrimestre:3,  requisitos:[11] },
  { id:14, nombre:'Electrónica Digital 1',  cuatrimestre:3,  requisitos:[4, 6, 7] },
  { id:15, nombre:'Física 2',               cuatrimestre:3,  requisitos:[8, 9] },
  { id:16, nombre:'Electrónica Digital 2',  cuatrimestre:4,  requisitos:[14] },
  { id:17, nombre:'Electrónica',            cuatrimestre:4,  requisitos:[6, 15] },
  { id:18, nombre:'Análisis Mat. 3',        cuatrimestre:4,  requisitos:[12] },
  { id:19, nombre:'Prob. y Estadística',    cuatrimestre:4,  requisitos:[5] },
  { id:20, nombre:'Bases de Datos',         cuatrimestre:5,  requisitos:[11] },
  { id:21, nombre:'Electrónica Digital 3',  cuatrimestre:5,  requisitos:[13, 16] },
  { id:22, nombre:'Ing. SW y HW',           cuatrimestre:5,  requisitos:[13, 16] },
  { id:23, nombre:'Señales y Sistemas',     cuatrimestre:5,  requisitos:[15, 18] },
  { id:24, nombre:'Sistemas de Control 1',  cuatrimestre:6,  requisitos:[23] },
  { id:25, nombre:'Redes de Computadoras',  cuatrimestre:6,  requisitos:[16] },
  { id:26, nombre:'Proc. de Señales',       cuatrimestre:6,  requisitos:[23] },
  { id:27, nombre:'Prog. Concurrente',      cuatrimestre:6,  requisitos:[13] },
  { id:28, nombre:'Sistemas Operativos',    cuatrimestre:7,  requisitos:[27] },
  { id:29, nombre:'Sistemas Embebidos',     cuatrimestre:7,  requisitos:[21] },
  { id:30, nombre:'Calidad de SW y HW',     cuatrimestre:7,  requisitos:[22] },
  { id:31, nombre:'Inteligencia Artificial',cuatrimestre:7,  requisitos:[22] },
  { id:32, nombre:'Seguridad Informática',  cuatrimestre:8,  requisitos:[30] },
  { id:33, nombre:'Sistemas Distribuidos',  cuatrimestre:8,  requisitos:[25, 28] },
  { id:34, nombre:'Arq. de Computadoras',   cuatrimestre:8,  requisitos:[28] },
  { id:35, nombre:'Sistemas de Control 2',  cuatrimestre:8,  requisitos:[24] },
  { id:36, nombre:'Sistemas Ciberfísicos',  cuatrimestre:9,  requisitos:[35] },
  { id:37, nombre:'Sistemas Informáticos',  cuatrimestre:9,  requisitos:[32] },
  { id:38, nombre:'Selectiva 1',            cuatrimestre:9,  requisitos:[] },
  { id:39, nombre:'Selectiva 2',            cuatrimestre:9,  requisitos:[] },
  { id:40, nombre:'Ing. Económica y Legal', cuatrimestre:10, requisitos:[22] },
  { id:41, nombre:'Higiene y Seguridad',    cuatrimestre:10, requisitos:[30] },
  { id:42, nombre:'Práctica Profesional',   cuatrimestre:10, requisitos:[] },
];

export const estructuraCurricular = [
  { anio:'Ingreso', cuatrimestres:[0] },
  { anio:'Año 1',   cuatrimestres:[1, 2] },
  { anio:'Año 2',   cuatrimestres:[3, 4] },
  { anio:'Año 3',   cuatrimestres:[5, 6] },
  { anio:'Año 4',   cuatrimestres:[7, 8] },
  { anio:'Año 5',   cuatrimestres:[9, 10] },
];

export const SELECTIVAS = new Set([38, 39]);
